name: Build App Debug

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout    
        uses: actions/checkout@v4
        
      - name: Add necessary properties into the local.properties
        run: |
          echo "apiBase=${{ secrets.API_BASE }}" >> local.properties
          echo "apiKey=${{ secrets.API_KEY }}" >> local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle          
                    
      - name: Compile Debug
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/*.apk
